apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: karimshaaban/expiration:latest
          imagePullPolicy: Never
          env:
            - name: NATS_URL # I know this is exposed, it's just a local nats server, i'd set it as a k8s secret in production
              value: 'nats://nats-srv:4222'
            - name: NATS_CLUSTER_ID # I know this is exposed, it's just a local nats server, i'd set it as a k8s secret in production
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #pod name will be used as client id
            - name: REDIS_HOST
              value: expiration-redis-srv