apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: karimshaaban/tickets:latest
          imagePullPolicy: Never
          env:
            - name: JWT_KEY # JWT secret key from k8s secret object, k8s pod will not start if this is not set
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI # I know this is exposed, it's just a local db, i'd set it as a k8s secret in production
              value: 'mongodb://tickets-mongo-srv:27017/tickets'

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP #default not a must
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
