name: tests-tickets
on: 
  pull_request:
    paths:
      - 'tickets/**' #only if anything inside auth dir is changed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
      